name: Strompreise automatisch aktualisieren

on:
  schedule:
    - cron: "5 23 * * *"   # täglich um 23:05 UTC (~01:05 MEZ)
  workflow_dispatch:       # auch manuell startbar

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Python installieren
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Abhängigkeiten installieren
        run: pip install pandas requests

      - name: Daten abrufen
        run: python strompreise.py

      - name: Commit & Push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          git add strompreise_awattar.csv
          git commit -m "📈 Update: $(date +'%Y-%m-%d')" || echo "♻️ Keine Änderungen"
          git push
